// src/components/client/DocumentReview.js
import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Grid,
  Chip,
  TextField,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Stepper,
  Step,
  StepLabel,
  Paper
} from '@mui/material';
import {
  ThumbUp as ApproveIcon,
  ThumbDown as RejectIcon,
  Comment as CommentIcon,
  Download as DownloadIcon
} from '@mui/icons-material';

const DocumentReview = () => {
  const [activeStep, setActiveStep] = useState(1);
  const [comments, setComments] = useState('');
  const [openCommentDialog, setOpenCommentDialog] = useState(false);

  const steps = ['Draft Created', 'Under Review', 'Client Feedback', 'Final Review', 'Completed'];

  const documentData = {
    title: 'Partnership Agreement - Dasion & Medical Clinic LLC',
    version: '2.1',
    lastUpdated: '2024-01-15',
    status: 'under_review',
    sections: [
      'Parties Definition',
      'Term and Termination',
      'Services and Responsibilities',
      'Compensation Structure',
      'Data Privacy and Compliance',
      'Intellectual Property',
      'Confidentiality',
      'Liability and Indemnification'
    ]
  };

  const handleApprove = () => {
    // Handle document approval
    setActiveStep(activeStep + 1);
  };

  const handleReject = () => {
    setOpenCommentDialog(true);
  };

  const submitFeedback = () => {
    // Submit feedback logic
    setOpenCommentDialog(false);
    setComments('');
  };

  return (
    <Box sx={{ p: 3 }}>
      <Typography variant="h4" gutterBottom sx={{ fontWeight: 600, mb: 4 }}>
        Document Review
      </Typography>

      <Grid container spacing={3}>
        {/* Document Header */}
        <Grid item xs={12}>
          <Card>
            <CardContent>
              <Box display="flex" justifyContent="space-between" alignItems="flex-start" mb={2}>
                <Box>
                  <Typography variant="h5" gutterBottom>
                    {documentData.title}
                  </Typography>
                  <Box display="flex" gap={2} alignItems="center">
                    <Chip label={`Version ${documentData.version}`} variant="outlined" />
                    <Typography variant="body2" color="textSecondary">
                      Last updated: {documentData.lastUpdated}
                    </Typography>
                    <Chip 
                      label={documentData.status.replace('_', ' ')} 
                      color="primary" 
                    />
                  </Box>
                </Box>
                <Button startIcon={<DownloadIcon />} variant="outlined">
                  Download PDF
                </Button>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        {/* Progress Stepper */}
        <Grid item xs={12}>
          <Card>
            <CardContent>
              <Stepper activeStep={activeStep} alternativeLabel>
                {steps.map((label) => (
                  <Step key={label}>
                    <StepLabel>{label}</StepLabel>
                  </Step>
                ))}
              </Stepper>
            </CardContent>
          </Card>
        </Grid>

        {/* Document Content & Actions */}
        <Grid item xs={12} md={8}>
          <Card sx={{ height: '400px', mb: 2 }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Document Preview
              </Typography>
              <Paper 
                variant="outlined" 
                sx={{ 
                  p: 3, 
                  height: '300px', 
                  overflow: 'auto',
                  backgroundColor: 'grey.50'
                }}
              >
                <Typography variant="body1" paragraph>
                  This is a simulated preview of the legal document. In the actual implementation, 
                  this would display the generated legal agreement with all terms and conditions 
                  extracted from the lawyer-client consultation.
                </Typography>
                
                <Typography variant="h6" gutterBottom sx={{ mt: 2 }}>
                  Key Sections:
                </Typography>
                <ul>
                  {documentData.sections.map((section, index) => (
                    <li key={index}>
                      <Typography variant="body2">{section}</Typography>
                    </li>
                  ))}
                </ul>

                <Typography variant="body2" sx={{ mt: 2, fontStyle: 'italic' }}>
                  [Document content generated by AI based on consultation transcription...]
                </Typography>
              </Paper>
            </CardContent>
          </Card>
        </Grid>

        {/* Review Actions */}
        <Grid item xs={12} md={4}>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Review Actions
              </Typography>
              
              <Box sx={{ '& > *': { mb: 2 } }}>
                <Button
                  variant="contained"
                  color="success"
                  startIcon={<ApproveIcon />}
                  onClick={handleApprove}
                  fullWidth
                  size="large"
                >
                  Approve Document
                </Button>

                <Button
                  variant="outlined"
                  color="error"
                  startIcon={<RejectIcon />}
                  onClick={handleReject}
                  fullWidth
                  size="large"
                >
                  Request Changes
                </Button>

                <Button
                  variant="outlined"
                  startIcon={<CommentIcon />}
                  fullWidth
                >
                  Add General Comments
                </Button>
              </Box>

              {/* Previous Comments */}
              <Box sx={{ mt: 3 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Previous Feedback
                </Typography>
                <Paper variant="outlined" sx={{ p: 2, backgroundColor: 'grey.50' }}>
                  <Typography variant="body2">
                    "Please clarify the data ownership terms in section 5.2 and update the termination notice period from 30 to 60 days."
                  </Typography>
                  <Typography variant="caption" color="textSecondary">
                    - Dr. Sarah Johnson, Jan 14, 2024
                  </Typography>
                </Paper>
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Comment Dialog */}
      <Dialog open={openCommentDialog} onClose={() => setOpenCommentDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Request Changes</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="textSecondary" gutterBottom>
            Please provide specific feedback on what changes are needed in the document.
          </Typography>
          <TextField
            autoFocus
            multiline
            rows={4}
            fullWidth
            value={comments}
            onChange={(e) => setComments(e.target.value)}
            placeholder="Describe the required changes, specify sections, and provide any additional context..."
            sx={{ mt: 2 }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenCommentDialog(false)}>Cancel</Button>
          <Button onClick={submitFeedback} variant="contained">
            Submit Feedback
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default DocumentReview;